### ISSUE TITLE
About "fileopt"

### ISSUE THREAD

**Issue by kingsleyluoxin** [plotly/documentation#1200]
Hello, I noticed that the keyword "fileopt" for py.plot and py.iplot has been removed. I want to update the same plot object in jupyter notebook. Does anyone have the solution?

**Comment by michaelbabyn** [comment]
There are two versions for both `iplot` and `plot` in the `plotly.py` library. One comes from `plotly.plotly` which sends plots to Chart Studio (these versions take the "fileopt" keyword) and the other come from `plotly.offline` which don't take the "fileopt" keyword since the plot is local to your machine and no url is created on Chart Studio for the plot.

@kingsleyluoxin , does that make sense?

**Comment by cldougl** [comment]
@kingsleyluoxin hopefully the above helped resolve your issue! Otherwise you're always welcome to post questions in our community forum: https://community.plot.ly/ 
We ask users to reserve github issues here to record issues with the documentation and ask usage questions in the forum. Thanks!
