### ISSUE TITLE
_config_dev.yml defaults are too restrictive and don't render most docs 

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/documentation#1306]

**Comment by cldougl** [comment]
@michaelbabyn the idea is that you can change the file as you're working but we won't push changes of this file in PRs

I'm in favour of leaving it relatively restricted because otherwise it takes quite a long time to render! But if you'd like to by default load some of the docs for example I think it's fine to change the config_dev file a bit.

**Comment by michaelbabyn** [comment]
I just wanted to revert it back to before this unrelated commit changed it to render almost nothing https://github.com/plotly/documentation/commit/9ab396d0907002b6ba783ef8a81558e8bae8b8e8#diff-7b582af8acdebcb0583b1f0944ff1f98

**Comment by cldougl** [comment]
that makes sense but I think it would be nice to be slightly more restrictive ie not rendering pandas, ggplot2, all the reference pages (I think rendering 1 reference page by default would suffice)
