### ISSUE TITLE
[python docs] Plotly Fundamentals reorg

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1360]
Given that the plan for the v4 docs is to use the current framework for final deployment, it makes sense to start the structural reorg in this repo now!

There are two related things I'd like to tackle first:

1. There are a bunch of pages in "Plotly Fundamentals" that are actually "Chart Studio Fundamentals" and should be de-emphasized/removed from the top of the docs
2. There are a bunch of pages lower down on the main page that are actually "Plotly Fundamentals" that should be moved up into a more prominent position like Legends, Axes, Subplots and various other styling-related pages

@michaelbabyn and I have been chatting about this and I'd love to workshop a list of the changes we could make here... If you could share what you've thought about so far Michael that would be helpful :)

**Comment by nicolaskruchten** [comment]
Here's a good candidate for the "chart studio" section :)

![image](https://user-images.githubusercontent.com/203523/59453749-8b401680-8dde-11e9-8c22-0b28a807ca7d.png)

**Comment by michaelbabyn** [comment]
I also think the current docs in  **Add custom controls** (Custom buttons, Sliders and Dropdown menus from) can go to the chart studio section as well since ipywidgets and FigureWidgets is the better/easier option offline. And everything currently in **fundamentals** aside from the 2 orca docs, the config doc and the jupyter notebook doc (although this one does have a few chart studio related sections) could be moved to chart studio.

**Comment by michaelbabyn** [comment]
When I was looking at other docs that would work best in fundamentals (from the current layout and style sections) this is the list i cam up with:

Axes, subplots, multiple axes, graph sizing, setting the titles, legends, text and annotations, text and font styling, hover text, Images, shapes, colorway, and one of the three colorscales docs. 

I also figured that since the above would break apart the layout section we could consolidate the 3D specific docs that are currently in the layout section into the 3D section.

**Comment by nicolaskruchten** [comment]
I'm good with making this change now. @cldougl thoughts?

**Comment by nicolaskruchten** [comment]
Related: any files impacted by the changes in https://github.com/plotly/plotly.py-docs/issues/16 should go into the "chart studio" bucket :)

**Comment by cldougl** [comment]
I'm good with this change!

**Comment by nicolaskruchten** [comment]
Great! @michaelbabyn this spreadsheet has certain pages tagged "chart studio" or "framework" that might be good candidates for getting shunted into Chart Studio or Fundamentals or an eventual "Advanced" category for the non-fundamental-yet-still-framework ones :)
