### ISSUE TITLE
alpha channel in fillcolor works in 1.8 but not in latest version 

### ISSUE THREAD

**Issue by BinaryInitials** [plotly/documentation#1390]
I recently tried to play with the fillcolor field. I tried making it transparent by using the alpha channel. 

`data = [{mode: 'lines', x: x, y: y1, line: {color: 'rgb(128,128,128)', width: 1}},{mode: 'lines', x: x, y: y2, line: {color: 'rgb(128,128,128)', width: 1}, fill: 'tonexty', fillcolor: '#9900CCCC'},]`

This should make the color region transparently turquoise. When I render this using 
`https://cdn.plot.ly/plotly-1.8.0.min.js` it works fine but when I use `https://cdn.plot.ly/plotly-latest.min.js` it doesn't work (i.e. color not transparent, alpha channel is ignored).

**Comment by cldougl** [comment]
Hi there,
Is there a documentation example that isn't working for you? Typically we ask users to reserve documentations issues for logging bugs in the documentation, otherwise we recommend posting user questions in our community forum: https://community.plot.ly/ 

The functionality of fillcolor seems to be working as expected: to set fillcolor opacity you can use the alpha channel as in the following example:
https://codepen.io/plotly/pen/bPxerV

**Comment by BinaryInitials** [comment]
my apologies! I will make sure to use the community forum in the future! 

It seems like the alpha channel wasn't working when I used the latest version of plotly but when I downgraded to an older version, the alpha channel took place. But now it seems to be working. Maybe I used the alpha number in the wrong channel. 

thank you for your reply.
