### ISSUE TITLE
github star button on js splash

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#224]
hey @delekru - I want to add a github stars button to the JS splash:

![image](https://cloud.githubusercontent.com/assets/1280389/11245499/0d2f7f98-8de1-11e5-9db0-addbde1feb85.png)

thoughts on where to place it?

**Comment by delekru** [comment]
I just made this real quick, but what do you think about putting it right on the banner? There's enough space because I designed it to have room for buttons underneath the subtitle.

It would work if it's positioned next to a 'github' button so people won't get confused.

![screen shot 2015-11-18 at 11 24 16 am](https://cloud.githubusercontent.com/assets/11370069/11246764/0dc7ac2c-8de7-11e5-9079-f396bd4284c1.png)

What do you think?

**Comment by chriddyp** [comment]
that sounds good. We don't actually have those buttons on the banner right now though

**Comment by delekru** [comment]
yeah totally. do you like the buttons there, or should we think of another place to put the github star?

**Comment by chriddyp** [comment]
closed via https://github.com/plotly/documentation/commit/b1eb3c19ec4912e0fe2001372ab2a1d3fb414c40
