### ISSUE TITLE
Function reference hard to read

### ISSUE THREAD

**Issue by fresheneesz** [plotly/documentation#543]
First of all, where is [this page](https://plot.ly/javascript/plotlyjs-function-reference/ ) in here? I can't find it.

Second of all, that page is incredibly annoying with its "do this thing with Plotly.whatever". Just write down the function name, not some cutsie sentence. It makes it really hard to find info on functions.

**Comment by cldougl** [comment]
Hi there, 
That page is located [here](https://github.com/plotly/documentation/blob/source-design-merge/_posts/2016-06-03-plotly_js_function_ref.html) in this repo.
Thanks for the feedback! Some of the titles may seem repetitive in relation to the function name, though I believe the pattern was originally started to be informative (rather than 'cutsie') for new users.

**Comment by fresheneesz** [comment]
Its certainly informative, but it makes the page (including the TOC0 difficult to visually parse.

**Comment by fresheneesz** [comment]
I'd suggest changing the format for `<code>` nodes inside headers. Right now you essentially see: PLOT WITH plotly.newPlot , when Plotly.newPlot is the important thing that should be large and blue.

**Comment by fresheneesz** [comment]
https://github.com/plotly/documentation/pull/549
