### ISSUE TITLE
Flesh out ggplot2 chart types in new API docs repo

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#63]
At sales demos, folks who use ggplot2 in general have no interest in Plotly's native R library.

Can we make an equivalent ggplot2 example for every plot.ly/R chart type at the new API documentation repo - https://github.com/plotly/documentation/tree/gh-pages?

For example, there is not ggplot2 hover text example equivalent to:
https://plot.ly/r/text-and-annotations/

Would be cool to reach parity between ggplot2 and plot.ly/R chart types. Its pretty cumbersome right now to demo ggplot2 functionality in sales meetings - ideally there are just copy/paste examples with the same breadth as https://plot.ly/r/

**Comment by mkcor** [comment]
Funny, this is from a recent email thread of mine with user Agus:
"""
Hi again Agus,

Sure, please use the `text` aesthetic:
```
gg <- ggplot(data=df) +
  geom_point(aes(x=mpg, y=hp, text=ID, color=cyl))

py <- plotly()

py$ggplotly(gg, kwargs=list(filename="ID_tooltip", fileopt="overwrite"))
```
which yields https://plot.ly/~marianne2/1415

Let me know if you have other questions!

Cheers,
Marianne
"""

> 3. Where did you get the information on argument "text" within
> geom_point()? I had never seen it
> and actually does not have any visual effect on the ggplot graphic.
> Thanks
> Agus

"""
I didn't find it in the ggplot2 docs... but it works syntax-wise
(btw, I like this tool:
http://cpsievert.github.io/2014/06/visualizing-ggplot2-internals-with-shiny-and-d3/)
and it's supported in plotly:
https://plot.ly/r/reference/#scatter-text
"""
and I Bcc'ed @cpsievert.

**Comment by cpsievert** [comment]
> At sales demos, folks who use ggplot2 in general have no interest in Plotly's native R library.

As an avid ggplot2/R user, I can relate, but I think if we provide a cleaner interface with smart defaults, it would be more attractive. I'd like to play around with idea in my [redesign the R API](https://github.com/ropensci/plotly/pull/217). For instance, I think creating a 3D surface plots (which the ggplot2 DSL doesn't natively support) could be as easy as:

```r
library(plotly)
plotly(volcano, type = "surface")
```

Since the redesign will effect documentation, I'd like to focus on the redesign first. 

By the way, I was anticipating to see that documentation show up here, but it doesn't, am I missing something? -> http://plotly.github.io/documentation

We could also utilize the gh-pages branch on the R package repo for documentation (which currently doesn't have very much). I have [some experience powering Jekyll blogs with knitr](http://cpsievert.github.io/knitr-jekyll//2015/04/jekyll-tufte-servr.html), so that's an option too.

cc @chriddyp @baobao

**Comment by jackparmer** [comment]
+1! This would be awesome @cpsievert 
```
library(plotly)
plotly(volcano, type = "surface")
```
